fatal: [vegeta01_temp]: UNREACHABLE! => {"changed": false, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo /root/tmp/ansible-tmp-1551393271.4257357-180668090450408 `\" && echo ansible-tmp-1551393271.4257357-180668090450408=\"` echo /root/tmp/ansible-tmp-1551393271.4257357-180668090450408 `\" ), exited with result 16, stdout output: Syntax error while parsing '/bin/sh -c '( umask 77 && mkdir -p \"` echo /root/tmp/ansible-tmp-1551393271.4257357-180668090450408 `\" && echo ansible-tmp-1551393271.4257357-180668090450408=\"` echo /root/tmp/ansible-tmp-1551393271.4257357-180668090450408 `\" ) && sleep 0''\n\n\nCmd exec error.\n", "unreachable": true}
to retry, use: --limit @/etc/ansible/playbooks/vlan.retry
